parameters:
#    cpseapi_user.example.class: CPSE\API\UserBundle\Example

services:
#    cpseapi_user.example:
#        class: %cpseapi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
